using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyTitleAttribute("NAnt")]
[assembly: AssemblyDescriptionAttribute("A .NET Build Tool")]
[assembly: AssemblyConfigurationAttribute("dev")]
[assembly: AssemblyCompanyAttribute("http://nant.sourceforge.net")]
[assembly: AssemblyProductAttribute("NAnt")]
[assembly: AssemblyCopyrightAttribute("Copyright (C) 2001-2016 Gerry Shaw")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]
[assembly: AssemblyVersionAttribute("0.93.6107.0")]
[assembly: AssemblyInformationalVersionAttribute("0.93")]

